---
# title: "Example"
# author: "Som Bohora"
# date: "July 18, 2017"
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### sAUC in Python (saucpy)

#### Perform AUC analyses with discrete covariates and a semi-parametric estimation

To illustrate how to apply the proposed method, we obtained data from a randomized and controlled clinical trial, which was designed to increase knowledge and awareness to prevent Fetal Alcohol Spectrum Disorders (FASD) in children through the development of printed materials targeting women of childbearing age in Russia. One of the study objectives was to evaluate effects of FASD education brochures with different types of information and visual images on FASD related knowledge, attitudes, and alcohol consumption on childbearing-aged women. The study was conducted in two regions in Russia including St. Petersburg (SPB) and the Nizhny Novgorod Region (NNR) from 2005 to 2008. A total of 458 women were recruited from women's clinics and were randomly assigned to one of three groups (defined by the GROUP variable): (1) a printed FASD prevention brochure with positive images and information stated in a positive way, positive group (PG), (2) a FASD education brochure with negative messages and vivid images, negative group (NG); and (3) a general health material, control group (CG). For the purpose of the analysis in this thesis, only women in the PG and CG were included. Data were obtained from the study principal investigators . The response variable was the change in the number of drinks per day (CHANGE_DRINK=number of drinks after-number of drinks before) on average in the last 30 days from one-month follow-up to baseline. Two covariates considered for the proposed method were "In the last 30 days, have you smoked cigarettes?" (SMOKE) and  "In the last 30 days, did you take any other vitamins?" (OVITAMIN). Both covariates had "Yes" or "No" as the two levels. The question of interest here was to assess the joint predictive effects of SMOKE and OVITAMIN on whether the participants reduced the number of drinks per day from baseline to one month follow-up period. A total of 210 women with no missing data on any of the CHANGE_DRINK, SMOKE, GROUP, and OVITAMIN were included in the analysis.

The response variable CHANGE_DRINK was heavily skewed and not normally distributed in each group  (Shapiro-Wilk p<0.001). Therefore, we decided to use the AUG regression model to analyze the data.  In the AUG regression model we define
$$\LARGE \pi = p(Y_{CG} > Y_{PG})$$ Note that the value of $\Large \pi$ greater than .5 means that women in the PG had a greater reduction of alcohol drinks than those in the CG. For statistical results, all p-values < .05 were considered statistically significant and 95% CIs were presented.

### Installation
`$ pip install saucpy`

`$ git clone https://github.com/sbohora/saucpy.git`


### Result of sAUC Regression with one discrete covariate

```python
from pandas import read_csv
from saucpy import sAUC

# Data analysis
fasd = read_csv("../saucpy/data/fasd.csv")
fasd['group'] = fasd['group'].astype('category')
fasd['x1']    = fasd['x1'].astype('category')
fasd['x2']    = fasd['x2'].astype('category')

sAUC.semiparametricAUC(response = "y", treatment_group = ["group"], input_covariates = ["x1"], data = fasd)
```

```
Model Summary
Out[13]: 
           Coefficients  Std. Error      2.5%     97.5%  Pr(>|z|)
Intercept     -0.909936    0.315218 -1.527751 -0.292121  0.003893
x1[T.2]        0.766786    0.356420  0.068216  1.465356  0.031448
```

### Result of sAUC Regression with two discrete covariates

```python
sAUC.semiparametricAUC(response = "y", treatment_group = ["group"], input_covariates = ["x1","x2"], data = fasd)
```

```
Model Summary
Out[14]: 
           Coefficients  Std. Error      2.5%     97.5%  Pr(>|z|)
Intercept     -1.125352    0.412748 -1.934324 -0.316380  0.006401
x1[T.2]        0.781264    0.355340  0.084809  1.477718  0.027904
x2[T.2]        0.252050    0.328229 -0.391267  0.895368  0.442541
```
